// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sobel,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.129000,HLS_SYN_LAT=303774,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=2,HLS_SYN_FF=1485,HLS_SYN_LUT=2716,HLS_VERSION=2018_3}" *)

module sobel (
        ap_clk,
        ap_rst_n,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        input_r_TKEEP,
        input_r_TSTRB,
        input_r_TLAST,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY,
        output_r_TKEEP,
        output_r_TSTRB,
        output_r_TLAST,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_pp0_stage0 = 8'd2;
parameter    ap_ST_fsm_pp0_stage1 = 8'd4;
parameter    ap_ST_fsm_pp0_stage2 = 8'd8;
parameter    ap_ST_fsm_pp0_stage3 = 8'd16;
parameter    ap_ST_fsm_pp0_stage4 = 8'd32;
parameter    ap_ST_fsm_pp0_stage5 = 8'd64;
parameter    ap_ST_fsm_state31 = 8'd128;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [7:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
input  [0:0] input_r_TKEEP;
input  [0:0] input_r_TSTRB;
input  [0:0] input_r_TLAST;
output  [7:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;
output  [0:0] output_r_TKEEP;
output  [0:0] output_r_TSTRB;
output  [0:0] output_r_TLAST;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [7:0] input_V_data_V_0_data_out;
wire    input_V_data_V_0_vld_in;
wire    input_V_data_V_0_vld_out;
wire    input_V_data_V_0_ack_in;
reg    input_V_data_V_0_ack_out;
reg   [7:0] input_V_data_V_0_payload_A;
reg   [7:0] input_V_data_V_0_payload_B;
reg    input_V_data_V_0_sel_rd;
reg    input_V_data_V_0_sel_wr;
wire    input_V_data_V_0_sel;
wire    input_V_data_V_0_load_A;
wire    input_V_data_V_0_load_B;
reg   [1:0] input_V_data_V_0_state;
wire    input_V_data_V_0_state_cmp_full;
wire    input_V_last_V_0_vld_in;
reg    input_V_last_V_0_ack_out;
reg   [1:0] input_V_last_V_0_state;
reg   [7:0] output_V_data_V_1_data_in;
reg   [7:0] output_V_data_V_1_data_out;
reg    output_V_data_V_1_vld_in;
wire    output_V_data_V_1_vld_out;
wire    output_V_data_V_1_ack_in;
wire    output_V_data_V_1_ack_out;
reg   [7:0] output_V_data_V_1_payload_A;
reg   [7:0] output_V_data_V_1_payload_B;
reg    output_V_data_V_1_sel_rd;
reg    output_V_data_V_1_sel_wr;
wire    output_V_data_V_1_sel;
wire    output_V_data_V_1_load_A;
wire    output_V_data_V_1_load_B;
reg   [1:0] output_V_data_V_1_state;
wire    output_V_data_V_1_state_cmp_full;
wire   [0:0] output_V_keep_V_1_data_out;
reg    output_V_keep_V_1_vld_in;
wire    output_V_keep_V_1_vld_out;
wire    output_V_keep_V_1_ack_in;
wire    output_V_keep_V_1_ack_out;
reg    output_V_keep_V_1_sel_rd;
wire    output_V_keep_V_1_sel;
reg   [1:0] output_V_keep_V_1_state;
wire   [0:0] output_V_strb_V_1_data_out;
reg    output_V_strb_V_1_vld_in;
wire    output_V_strb_V_1_vld_out;
wire    output_V_strb_V_1_ack_in;
wire    output_V_strb_V_1_ack_out;
reg    output_V_strb_V_1_sel_rd;
wire    output_V_strb_V_1_sel;
reg   [1:0] output_V_strb_V_1_state;
reg   [0:0] output_V_last_V_1_data_in;
reg   [0:0] output_V_last_V_1_data_out;
reg    output_V_last_V_1_vld_in;
wire    output_V_last_V_1_vld_out;
wire    output_V_last_V_1_ack_in;
wire    output_V_last_V_1_ack_out;
reg   [0:0] output_V_last_V_1_payload_A;
reg   [0:0] output_V_last_V_1_payload_B;
reg    output_V_last_V_1_sel_rd;
reg    output_V_last_V_1_sel_wr;
wire    output_V_last_V_1_sel;
wire    output_V_last_V_1_load_A;
wire    output_V_last_V_1_load_B;
reg   [1:0] output_V_last_V_1_state;
wire    output_V_last_V_1_state_cmp_full;
reg    input_r_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage5;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage5;
reg   [0:0] exitcond1_reg_804;
reg    output_r_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_enable_reg_pp0_iter4;
wire    ap_block_pp0_stage3;
reg   [0:0] or_cond_reg_825;
reg   [0:0] or_cond_reg_825_pp0_iter4_reg;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] or_cond_reg_825_pp0_iter3_reg;
reg   [31:0] row_reg_233;
reg  signed [31:0] col_reg_245;
reg   [15:0] i_reg_257;
wire   [7:0] line_buffer_q0;
reg   [7:0] reg_282;
wire    ap_block_state5_pp0_stage3_iter0;
wire    ap_block_state11_pp0_stage3_iter1;
wire    ap_block_state17_pp0_stage3_iter2;
wire    ap_block_state23_pp0_stage3_iter3;
wire    ap_block_state29_pp0_stage3_iter4;
reg    ap_block_state29_io;
reg    ap_block_pp0_stage3_11001;
wire   [7:0] line_buffer_q1;
wire    ap_block_state6_pp0_stage4_iter0;
wire    ap_block_state12_pp0_stage4_iter1;
wire    ap_block_state18_pp0_stage4_iter2;
wire    ap_block_state24_pp0_stage4_iter3;
reg    ap_block_state24_io;
wire    ap_block_state30_pp0_stage4_iter4;
reg    ap_block_state30_io;
reg    ap_block_pp0_stage4_11001;
reg    ap_block_state7_pp0_stage5_iter0;
wire    ap_block_state13_pp0_stage5_iter1;
wire    ap_block_state19_pp0_stage5_iter2;
wire    ap_block_state25_pp0_stage5_iter3;
reg    ap_block_state25_io;
reg    ap_block_pp0_stage5_11001;
wire   [0:0] exitcond1_fu_287_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state8_pp0_stage0_iter1;
wire    ap_block_state14_pp0_stage0_iter2;
wire    ap_block_state20_pp0_stage0_iter3;
wire    ap_block_state26_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] i_1_fu_293_p2;
reg   [15:0] i_1_reg_808;
reg   [9:0] line_buffer_addr_reg_813;
reg   [9:0] line_buffer_addr_2_reg_819;
wire   [0:0] or_cond_fu_357_p2;
reg   [0:0] or_cond_reg_825_pp0_iter1_reg;
reg   [0:0] or_cond_reg_825_pp0_iter2_reg;
wire   [0:0] grp_fu_276_p2;
reg   [0:0] tmp_last_V_1_reg_829;
reg   [0:0] tmp_last_V_1_reg_829_pp0_iter1_reg;
reg   [0:0] tmp_last_V_1_reg_829_pp0_iter2_reg;
reg   [0:0] tmp_last_V_1_reg_829_pp0_iter3_reg;
reg   [0:0] tmp_last_V_reg_834;
reg   [0:0] tmp_last_V_reg_834_pp0_iter1_reg;
reg   [0:0] tmp_last_V_reg_834_pp0_iter2_reg;
reg   [0:0] tmp_last_V_reg_834_pp0_iter3_reg;
reg   [0:0] tmp_last_V_reg_834_pp0_iter4_reg;
wire   [10:0] tmp_23_fu_379_p1;
reg   [10:0] tmp_23_reg_839;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state4_pp0_stage2_iter0;
wire    ap_block_state10_pp0_stage2_iter1;
wire    ap_block_state16_pp0_stage2_iter2;
wire    ap_block_state22_pp0_stage2_iter3;
wire    ap_block_state28_pp0_stage2_iter4;
wire    ap_block_pp0_stage2_11001;
wire   [31:0] tmp_31_0_1_fu_394_p2;
reg   [31:0] tmp_31_0_1_reg_854;
wire   [10:0] tmp_27_fu_400_p1;
reg   [10:0] tmp_27_reg_859;
reg   [7:0] line_buffer_load_5_reg_869;
wire   [31:0] p_row_fu_427_p3;
reg   [31:0] p_row_reg_874;
wire   [31:0] p_s_fu_435_p3;
reg   [31:0] p_s_reg_879;
wire   [8:0] tmp_6_fu_465_p2;
reg   [8:0] tmp_6_reg_894;
wire   [8:0] sum_fu_471_p2;
reg   [8:0] sum_reg_899;
wire   [10:0] gx_fu_552_p2;
reg   [10:0] gx_reg_909;
wire   [9:0] tmp_13_fu_567_p2;
reg   [9:0] tmp_13_reg_914;
wire   [10:0] gy_fu_609_p2;
reg   [10:0] gy_reg_919;
wire  signed [21:0] tmp_15_fu_791_p2;
reg  signed [21:0] tmp_15_reg_924;
wire  signed [21:0] grp_fu_797_p3;
reg  signed [21:0] tmp_17_reg_929;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state9_pp0_stage1_iter1;
wire    ap_block_state15_pp0_stage1_iter2;
wire    ap_block_state21_pp0_stage1_iter3;
wire    ap_block_state27_pp0_stage1_iter4;
wire    ap_block_pp0_stage1_11001;
wire   [31:0] grp_fu_268_p1;
reg   [31:0] tmp_18_reg_939;
wire   [31:0] grp_fu_271_p2;
reg   [31:0] x_assign_reg_944;
reg   [0:0] p_Result_s_reg_949;
wire   [31:0] p_Val2_5_fu_743_p3;
reg   [31:0] p_Val2_5_reg_954;
wire   [7:0] tmp_data_V_fu_782_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_enable_reg_pp0_iter2;
reg   [9:0] line_buffer_address0;
reg    line_buffer_ce0;
reg    line_buffer_we0;
reg   [7:0] line_buffer_d0;
reg   [9:0] line_buffer_address1;
reg    line_buffer_ce1;
reg    line_buffer_we1;
reg   [31:0] ap_phi_mux_row_phi_fu_237_p4;
wire    ap_block_pp0_stage0;
reg  signed [31:0] ap_phi_mux_col_phi_fu_249_p4;
reg   [15:0] ap_phi_mux_i_phi_fu_261_p4;
wire  signed [63:0] tmp_22_cast_fu_309_p1;
wire  signed [63:0] tmp_23_cast_fu_320_p1;
wire  signed [63:0] tmp_1_fu_363_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] tmp_5_fu_374_p1;
wire    ap_block_pp0_stage2;
wire  signed [63:0] tmp_24_cast_fu_389_p1;
wire   [63:0] tmp_32_0_2_fu_404_p1;
wire  signed [63:0] tmp_25_cast_fu_448_p1;
wire   [63:0] tmp_32_0_1_fu_453_p1;
wire  signed [63:0] tmp_26_cast_fu_487_p1;
wire    ap_block_pp0_stage4_01001;
wire    ap_block_pp0_stage3_01001;
wire  signed [31:0] grp_fu_268_p0;
wire   [10:0] tmp_2_fu_299_p1;
wire   [10:0] tmp_3_fu_303_p2;
wire   [10:0] tmp_19_fu_314_p2;
wire   [30:0] tmp_20_fu_325_p4;
wire   [30:0] tmp_22_fu_341_p4;
wire   [0:0] icmp_fu_335_p2;
wire   [0:0] icmp4_fu_351_p2;
wire   [31:0] tmp_4_fu_368_p2;
wire   [10:0] tmp_24_fu_383_p2;
wire   [31:0] col_1_fu_409_p2;
wire   [0:0] tmp_21_fu_415_p2;
wire   [31:0] row_1_fu_421_p2;
wire   [10:0] tmp_25_fu_443_p2;
wire   [8:0] tmp_6_cast_fu_461_p1;
wire   [8:0] tmp_5_cast_fu_457_p1;
wire   [10:0] tmp_26_fu_482_p2;
wire   [8:0] tmp_8_fu_492_p3;
wire   [8:0] tmp_s_fu_503_p3;
wire  signed [10:0] tmp_11_cast_fu_531_p1;
wire   [10:0] tmp_8_cast_fu_499_p1;
wire   [10:0] tmp_cast_fu_511_p1;
wire   [10:0] tmp_7_fu_534_p2;
wire   [10:0] tmp_9_fu_540_p2;
wire   [10:0] tmp_4_cast_fu_519_p1;
wire   [10:0] tmp_10_cast_fu_527_p1;
wire   [10:0] tmp_10_fu_546_p2;
wire   [9:0] tmp_4_cast4_fu_515_p1;
wire   [9:0] sum_cast_fu_558_p1;
wire   [9:0] tmp_10_cast3_fu_523_p1;
wire   [9:0] sum87_neg_fu_561_p2;
wire   [8:0] tmp_11_fu_576_p3;
wire   [8:0] tmp_12_fu_588_p3;
wire  signed [10:0] tmp_19_cast_fu_600_p1;
wire   [10:0] tmp_16_cast_fu_584_p1;
wire   [10:0] tmp_18_cast_fu_596_p1;
wire   [10:0] tmp_14_fu_603_p2;
wire   [31:0] p_Val2_s_fu_622_p1;
wire   [22:0] tmp_V_1_fu_643_p1;
wire   [24:0] mantissa_V_fu_647_p4;
wire   [7:0] tmp_V_fu_633_p4;
wire   [8:0] tmp_i_i_i_i_cast1_fu_661_p1;
wire   [8:0] sh_assign_fu_665_p2;
wire   [7:0] tmp_i_i_i_fu_679_p2;
wire   [0:0] isNeg_fu_671_p3;
wire  signed [8:0] tmp_i_i_i_cast_fu_685_p1;
wire  signed [8:0] ush_fu_689_p3;
wire  signed [31:0] sh_assign_2_cast_fu_697_p1;
wire  signed [24:0] sh_assign_2_cast_cas_fu_701_p1;
wire   [78:0] mantissa_V_1_cast2_fu_657_p1;
wire   [78:0] tmp_i_i_i_8_fu_705_p1;
wire   [24:0] r_V_fu_709_p2;
wire   [0:0] tmp_34_fu_721_p3;
wire   [78:0] r_V_1_fu_715_p2;
wire   [31:0] tmp_29_fu_729_p1;
wire   [31:0] tmp_30_fu_733_p4;
wire   [31:0] result_V_1_fu_751_p2;
wire   [31:0] p_Val2_6_fu_756_p3;
wire   [23:0] tmp_35_fu_762_p4;
wire   [0:0] icmp9_fu_772_p2;
wire   [7:0] tmp_36_fu_778_p1;
wire  signed [10:0] tmp_15_fu_791_p0;
wire  signed [21:0] gx_cast_cast_fu_573_p1;
wire  signed [10:0] tmp_15_fu_791_p1;
wire  signed [10:0] grp_fu_797_p0;
wire  signed [21:0] gy_cast_cast_fu_615_p1;
wire  signed [10:0] grp_fu_797_p1;
reg    grp_fu_268_ce;
reg    grp_fu_271_ce;
wire    ap_CS_fsm_state31;
reg    ap_block_state31;
reg   [7:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 input_V_data_V_0_sel_rd = 1'b0;
#0 input_V_data_V_0_sel_wr = 1'b0;
#0 input_V_data_V_0_state = 2'd0;
#0 input_V_last_V_0_state = 2'd0;
#0 output_V_data_V_1_sel_rd = 1'b0;
#0 output_V_data_V_1_sel_wr = 1'b0;
#0 output_V_data_V_1_state = 2'd0;
#0 output_V_keep_V_1_sel_rd = 1'b0;
#0 output_V_keep_V_1_state = 2'd0;
#0 output_V_strb_V_1_sel_rd = 1'b0;
#0 output_V_strb_V_1_state = 2'd0;
#0 output_V_last_V_1_sel_rd = 1'b0;
#0 output_V_last_V_1_sel_wr = 1'b0;
#0 output_V_last_V_1_state = 2'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

sobel_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
sobel_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

sobel_line_buffer #(
    .DataWidth( 8 ),
    .AddressRange( 675 ),
    .AddressWidth( 10 ))
line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_address0),
    .ce0(line_buffer_ce0),
    .we0(line_buffer_we0),
    .d0(line_buffer_d0),
    .q0(line_buffer_q0),
    .address1(line_buffer_address1),
    .ce1(line_buffer_ce1),
    .we1(line_buffer_we1),
    .d1(line_buffer_q1),
    .q1(line_buffer_q1)
);

sobel_sitofp_32s_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sobel_sitofp_32s_bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_268_p0),
    .ce(grp_fu_268_ce),
    .dout(grp_fu_268_p1)
);

sobel_fsqrt_32ns_cud #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sobel_fsqrt_32ns_cud_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(32'd0),
    .din1(tmp_18_reg_939),
    .ce(grp_fu_271_ce),
    .dout(grp_fu_271_p2)
);

sobel_mul_mul_11sdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 22 ))
sobel_mul_mul_11sdEe_U3(
    .din0(tmp_15_fu_791_p0),
    .din1(tmp_15_fu_791_p1),
    .dout(tmp_15_fu_791_p2)
);

sobel_mac_muladd_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
sobel_mac_muladd_eOg_U4(
    .din0(grp_fu_797_p0),
    .din1(grp_fu_797_p1),
    .din2(tmp_15_reg_924),
    .dout(grp_fu_797_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((input_V_data_V_0_ack_out == 1'b1) & (input_V_data_V_0_vld_out == 1'b1))) begin
            input_V_data_V_0_sel_rd <= ~input_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((input_V_data_V_0_ack_in == 1'b1) & (input_V_data_V_0_vld_in == 1'b1))) begin
            input_V_data_V_0_sel_wr <= ~input_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((input_V_data_V_0_state == 2'd2) & (input_V_data_V_0_vld_in == 1'b0)) | ((input_V_data_V_0_state == 2'd3) & (input_V_data_V_0_vld_in == 1'b0) & (input_V_data_V_0_ack_out == 1'b1)))) begin
            input_V_data_V_0_state <= 2'd2;
        end else if ((((input_V_data_V_0_state == 2'd1) & (input_V_data_V_0_ack_out == 1'b0)) | ((input_V_data_V_0_state == 2'd3) & (input_V_data_V_0_ack_out == 1'b0) & (input_V_data_V_0_vld_in == 1'b1)))) begin
            input_V_data_V_0_state <= 2'd1;
        end else if (((~((input_V_data_V_0_vld_in == 1'b0) & (input_V_data_V_0_ack_out == 1'b1)) & ~((input_V_data_V_0_ack_out == 1'b0) & (input_V_data_V_0_vld_in == 1'b1)) & (input_V_data_V_0_state == 2'd3)) | ((input_V_data_V_0_state == 2'd1) & (input_V_data_V_0_ack_out == 1'b1)) | ((input_V_data_V_0_state == 2'd2) & (input_V_data_V_0_vld_in == 1'b1)))) begin
            input_V_data_V_0_state <= 2'd3;
        end else begin
            input_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((input_V_last_V_0_state == 2'd2) & (input_V_last_V_0_vld_in == 1'b0)) | ((input_V_last_V_0_state == 2'd3) & (input_V_last_V_0_vld_in == 1'b0) & (input_V_last_V_0_ack_out == 1'b1)))) begin
            input_V_last_V_0_state <= 2'd2;
        end else if ((((input_V_last_V_0_state == 2'd1) & (input_V_last_V_0_ack_out == 1'b0)) | ((input_V_last_V_0_state == 2'd3) & (input_V_last_V_0_ack_out == 1'b0) & (input_V_last_V_0_vld_in == 1'b1)))) begin
            input_V_last_V_0_state <= 2'd1;
        end else if (((~((input_V_last_V_0_vld_in == 1'b0) & (input_V_last_V_0_ack_out == 1'b1)) & ~((input_V_last_V_0_ack_out == 1'b0) & (input_V_last_V_0_vld_in == 1'b1)) & (input_V_last_V_0_state == 2'd3)) | ((input_V_last_V_0_state == 2'd1) & (input_V_last_V_0_ack_out == 1'b1)) | ((input_V_last_V_0_state == 2'd2) & (input_V_last_V_0_vld_in == 1'b1)))) begin
            input_V_last_V_0_state <= 2'd3;
        end else begin
            input_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_data_V_1_ack_out == 1'b1) & (output_V_data_V_1_vld_out == 1'b1))) begin
            output_V_data_V_1_sel_rd <= ~output_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_V_data_V_1_ack_in == 1'b1) & (output_V_data_V_1_vld_in == 1'b1))) begin
            output_V_data_V_1_sel_wr <= ~output_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_data_V_1_state == 2'd2) & (output_V_data_V_1_vld_in == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (output_V_data_V_1_vld_in == 1'b0) & (output_V_data_V_1_ack_out == 1'b1)))) begin
            output_V_data_V_1_state <= 2'd2;
        end else if ((((output_V_data_V_1_state == 2'd1) & (output_V_data_V_1_ack_out == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (output_V_data_V_1_ack_out == 1'b0) & (output_V_data_V_1_vld_in == 1'b1)))) begin
            output_V_data_V_1_state <= 2'd1;
        end else if (((~((output_V_data_V_1_vld_in == 1'b0) & (output_V_data_V_1_ack_out == 1'b1)) & ~((output_V_data_V_1_ack_out == 1'b0) & (output_V_data_V_1_vld_in == 1'b1)) & (output_V_data_V_1_state == 2'd3)) | ((output_V_data_V_1_state == 2'd1) & (output_V_data_V_1_ack_out == 1'b1)) | ((output_V_data_V_1_state == 2'd2) & (output_V_data_V_1_vld_in == 1'b1)))) begin
            output_V_data_V_1_state <= 2'd3;
        end else begin
            output_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_keep_V_1_ack_out == 1'b1) & (output_V_keep_V_1_vld_out == 1'b1))) begin
            output_V_keep_V_1_sel_rd <= ~output_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_keep_V_1_state == 2'd2) & (output_V_keep_V_1_vld_in == 1'b0)) | ((output_V_keep_V_1_state == 2'd3) & (output_V_keep_V_1_vld_in == 1'b0) & (output_V_keep_V_1_ack_out == 1'b1)))) begin
            output_V_keep_V_1_state <= 2'd2;
        end else if ((((output_V_keep_V_1_state == 2'd1) & (output_V_keep_V_1_ack_out == 1'b0)) | ((output_V_keep_V_1_state == 2'd3) & (output_V_keep_V_1_ack_out == 1'b0) & (output_V_keep_V_1_vld_in == 1'b1)))) begin
            output_V_keep_V_1_state <= 2'd1;
        end else if (((~((output_V_keep_V_1_vld_in == 1'b0) & (output_V_keep_V_1_ack_out == 1'b1)) & ~((output_V_keep_V_1_ack_out == 1'b0) & (output_V_keep_V_1_vld_in == 1'b1)) & (output_V_keep_V_1_state == 2'd3)) | ((output_V_keep_V_1_state == 2'd1) & (output_V_keep_V_1_ack_out == 1'b1)) | ((output_V_keep_V_1_state == 2'd2) & (output_V_keep_V_1_vld_in == 1'b1)))) begin
            output_V_keep_V_1_state <= 2'd3;
        end else begin
            output_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_last_V_1_ack_out == 1'b1) & (output_V_last_V_1_vld_out == 1'b1))) begin
            output_V_last_V_1_sel_rd <= ~output_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_V_last_V_1_ack_in == 1'b1) & (output_V_last_V_1_vld_in == 1'b1))) begin
            output_V_last_V_1_sel_wr <= ~output_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_last_V_1_state == 2'd2) & (output_V_last_V_1_vld_in == 1'b0)) | ((output_V_last_V_1_state == 2'd3) & (output_V_last_V_1_vld_in == 1'b0) & (output_V_last_V_1_ack_out == 1'b1)))) begin
            output_V_last_V_1_state <= 2'd2;
        end else if ((((output_V_last_V_1_state == 2'd1) & (output_V_last_V_1_ack_out == 1'b0)) | ((output_V_last_V_1_state == 2'd3) & (output_V_last_V_1_ack_out == 1'b0) & (output_V_last_V_1_vld_in == 1'b1)))) begin
            output_V_last_V_1_state <= 2'd1;
        end else if (((~((output_V_last_V_1_vld_in == 1'b0) & (output_V_last_V_1_ack_out == 1'b1)) & ~((output_V_last_V_1_ack_out == 1'b0) & (output_V_last_V_1_vld_in == 1'b1)) & (output_V_last_V_1_state == 2'd3)) | ((output_V_last_V_1_state == 2'd1) & (output_V_last_V_1_ack_out == 1'b1)) | ((output_V_last_V_1_state == 2'd2) & (output_V_last_V_1_vld_in == 1'b1)))) begin
            output_V_last_V_1_state <= 2'd3;
        end else begin
            output_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_V_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_strb_V_1_ack_out == 1'b1) & (output_V_strb_V_1_vld_out == 1'b1))) begin
            output_V_strb_V_1_sel_rd <= ~output_V_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_V_strb_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_strb_V_1_state == 2'd2) & (output_V_strb_V_1_vld_in == 1'b0)) | ((output_V_strb_V_1_state == 2'd3) & (output_V_strb_V_1_vld_in == 1'b0) & (output_V_strb_V_1_ack_out == 1'b1)))) begin
            output_V_strb_V_1_state <= 2'd2;
        end else if ((((output_V_strb_V_1_state == 2'd1) & (output_V_strb_V_1_ack_out == 1'b0)) | ((output_V_strb_V_1_state == 2'd3) & (output_V_strb_V_1_ack_out == 1'b0) & (output_V_strb_V_1_vld_in == 1'b1)))) begin
            output_V_strb_V_1_state <= 2'd1;
        end else if (((~((output_V_strb_V_1_vld_in == 1'b0) & (output_V_strb_V_1_ack_out == 1'b1)) & ~((output_V_strb_V_1_ack_out == 1'b0) & (output_V_strb_V_1_vld_in == 1'b1)) & (output_V_strb_V_1_state == 2'd3)) | ((output_V_strb_V_1_state == 2'd1) & (output_V_strb_V_1_ack_out == 1'b1)) | ((output_V_strb_V_1_state == 2'd2) & (output_V_strb_V_1_vld_in == 1'b1)))) begin
            output_V_strb_V_1_state <= 2'd3;
        end else begin
            output_V_strb_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1_reg_804 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_reg_245 <= p_s_reg_879;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        col_reg_245 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1_reg_804 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_257 <= i_1_reg_808;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_257 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (or_cond_reg_825 == 1'd1) & (exitcond1_reg_804 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        reg_282 <= line_buffer_q1;
    end else if ((((1'b0 == ap_block_pp0_stage3_11001) & (or_cond_reg_825 == 1'd1) & (exitcond1_reg_804 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (or_cond_reg_825 == 1'd1) & (exitcond1_reg_804 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        reg_282 <= line_buffer_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1_reg_804 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_reg_233 <= p_row_reg_874;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_reg_233 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond1_reg_804 <= exitcond1_fu_287_p2;
        or_cond_reg_825_pp0_iter1_reg <= or_cond_reg_825;
        or_cond_reg_825_pp0_iter2_reg <= or_cond_reg_825_pp0_iter1_reg;
        or_cond_reg_825_pp0_iter3_reg <= or_cond_reg_825_pp0_iter2_reg;
        or_cond_reg_825_pp0_iter4_reg <= or_cond_reg_825_pp0_iter3_reg;
        tmp_last_V_1_reg_829_pp0_iter1_reg <= tmp_last_V_1_reg_829;
        tmp_last_V_1_reg_829_pp0_iter2_reg <= tmp_last_V_1_reg_829_pp0_iter1_reg;
        tmp_last_V_1_reg_829_pp0_iter3_reg <= tmp_last_V_1_reg_829_pp0_iter2_reg;
        tmp_last_V_reg_834_pp0_iter1_reg <= tmp_last_V_reg_834;
        tmp_last_V_reg_834_pp0_iter2_reg <= tmp_last_V_reg_834_pp0_iter1_reg;
        tmp_last_V_reg_834_pp0_iter3_reg <= tmp_last_V_reg_834_pp0_iter2_reg;
        tmp_last_V_reg_834_pp0_iter4_reg <= tmp_last_V_reg_834_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (or_cond_reg_825 == 1'd1) & (exitcond1_reg_804 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        gx_reg_909 <= gx_fu_552_p2;
        tmp_13_reg_914 <= tmp_13_fu_567_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_cond_reg_825 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gy_reg_919 <= gy_fu_609_p2;
        tmp_15_reg_924 <= tmp_15_fu_791_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        i_1_reg_808 <= i_1_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((input_V_data_V_0_load_A == 1'b1)) begin
        input_V_data_V_0_payload_A <= input_r_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((input_V_data_V_0_load_B == 1'b1)) begin
        input_V_data_V_0_payload_B <= input_r_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1_fu_287_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_addr_2_reg_819 <= tmp_23_cast_fu_320_p1;
        line_buffer_addr_reg_813 <= tmp_22_cast_fu_309_p1;
        or_cond_reg_825 <= or_cond_fu_357_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (or_cond_reg_825 == 1'd1) & (exitcond1_reg_804 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        line_buffer_load_5_reg_869 <= line_buffer_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_data_V_1_load_A == 1'b1)) begin
        output_V_data_V_1_payload_A <= output_V_data_V_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_data_V_1_load_B == 1'b1)) begin
        output_V_data_V_1_payload_B <= output_V_data_V_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_last_V_1_load_A == 1'b1)) begin
        output_V_last_V_1_payload_A <= output_V_last_V_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_last_V_1_load_B == 1'b1)) begin
        output_V_last_V_1_payload_B <= output_V_last_V_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (or_cond_reg_825_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_Result_s_reg_949 <= p_Val2_s_fu_622_p1[32'd31];
        p_Val2_5_reg_954 <= p_Val2_5_fu_743_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (exitcond1_reg_804 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_row_reg_874 <= p_row_fu_427_p3;
        p_s_reg_879 <= p_s_fu_435_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (or_cond_reg_825 == 1'd1) & (exitcond1_reg_804 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        sum_reg_899 <= sum_fu_471_p2;
        tmp_6_reg_894 <= tmp_6_fu_465_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (or_cond_reg_825_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_17_reg_929 <= grp_fu_797_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (or_cond_reg_825_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_18_reg_939 <= grp_fu_268_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (or_cond_reg_825 == 1'd1) & (exitcond1_reg_804 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_23_reg_839 <= tmp_23_fu_379_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (or_cond_reg_825 == 1'd1) & (exitcond1_reg_804 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        tmp_27_reg_859 <= tmp_27_fu_400_p1;
        tmp_31_0_1_reg_854 <= tmp_31_0_1_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_cond_fu_357_p2 == 1'd0) & (exitcond1_fu_287_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        tmp_last_V_1_reg_829 <= grp_fu_276_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_cond_fu_357_p2 == 1'd1) & (exitcond1_fu_287_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        tmp_last_V_reg_834 <= grp_fu_276_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (or_cond_reg_825_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        x_assign_reg_944 <= grp_fu_271_p2;
    end
end

always @ (*) begin
    if ((exitcond1_fu_287_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((~((output_V_last_V_1_ack_in == 1'b0) | (output_V_strb_V_1_ack_in == 1'b0) | (output_V_keep_V_1_ack_in == 1'b0) | (output_V_data_V_1_ack_in == 1'b0)) & (output_V_last_V_1_state[1'd0] == 1'b0) & (output_V_strb_V_1_state[1'd0] == 1'b0) & (output_V_keep_V_1_state[1'd0] == 1'b0) & (output_V_data_V_1_state[1'd0] == 1'b0) & (1'b1 == ap_CS_fsm_state31))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond1_reg_804 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_col_phi_fu_249_p4 = p_s_reg_879;
    end else begin
        ap_phi_mux_col_phi_fu_249_p4 = col_reg_245;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond1_reg_804 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_i_phi_fu_261_p4 = i_1_reg_808;
    end else begin
        ap_phi_mux_i_phi_fu_261_p4 = i_reg_257;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond1_reg_804 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_row_phi_fu_237_p4 = p_row_reg_874;
    end else begin
        ap_phi_mux_row_phi_fu_237_p4 = row_reg_233;
    end
end

always @ (*) begin
    if ((~((output_V_last_V_1_ack_in == 1'b0) | (output_V_strb_V_1_ack_in == 1'b0) | (output_V_keep_V_1_ack_in == 1'b0) | (output_V_data_V_1_ack_in == 1'b0)) & (output_V_last_V_1_state[1'd0] == 1'b0) & (output_V_strb_V_1_state[1'd0] == 1'b0) & (output_V_keep_V_1_state[1'd0] == 1'b0) & (output_V_data_V_1_state[1'd0] == 1'b0) & (1'b1 == ap_CS_fsm_state31))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        grp_fu_268_ce = 1'b1;
    end else begin
        grp_fu_268_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        grp_fu_271_ce = 1'b1;
    end else begin
        grp_fu_271_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (exitcond1_reg_804 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        input_V_data_V_0_ack_out = 1'b1;
    end else begin
        input_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((input_V_data_V_0_sel == 1'b1)) begin
        input_V_data_V_0_data_out = input_V_data_V_0_payload_B;
    end else begin
        input_V_data_V_0_data_out = input_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (exitcond1_reg_804 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        input_V_last_V_0_ack_out = 1'b1;
    end else begin
        input_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_reg_804 == 1'd0) & (1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        input_r_TDATA_blk_n = input_V_data_V_0_state[1'd0];
    end else begin
        input_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            line_buffer_address0 = line_buffer_addr_2_reg_819;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            line_buffer_address0 = tmp_32_0_1_fu_453_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            line_buffer_address0 = tmp_32_0_2_fu_404_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            line_buffer_address0 = tmp_5_fu_374_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            line_buffer_address0 = tmp_1_fu_363_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            line_buffer_address0 = tmp_22_cast_fu_309_p1;
        end else begin
            line_buffer_address0 = 'bx;
        end
    end else begin
        line_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        line_buffer_address1 = tmp_26_cast_fu_487_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        line_buffer_address1 = tmp_25_cast_fu_448_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        line_buffer_address1 = tmp_24_cast_fu_389_p1;
    end else if ((((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
        line_buffer_address1 = line_buffer_addr_reg_813;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        line_buffer_address1 = tmp_23_cast_fu_320_p1;
    end else begin
        line_buffer_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        line_buffer_ce0 = 1'b1;
    end else begin
        line_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        line_buffer_ce1 = 1'b1;
    end else begin
        line_buffer_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            line_buffer_d0 = input_V_data_V_0_data_out;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            line_buffer_d0 = line_buffer_q0;
        end else begin
            line_buffer_d0 = 'bx;
        end
    end else begin
        line_buffer_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (exitcond1_reg_804 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (exitcond1_reg_804 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        line_buffer_we0 = 1'b1;
    end else begin
        line_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (exitcond1_reg_804 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        line_buffer_we1 = 1'b1;
    end else begin
        line_buffer_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_01001) & (or_cond_reg_825_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        output_V_data_V_1_data_in = tmp_data_V_fu_782_p3;
    end else if (((1'b0 == ap_block_pp0_stage4_01001) & (or_cond_reg_825_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        output_V_data_V_1_data_in = 8'd0;
    end else begin
        output_V_data_V_1_data_in = 'bx;
    end
end

always @ (*) begin
    if ((output_V_data_V_1_sel == 1'b1)) begin
        output_V_data_V_1_data_out = output_V_data_V_1_payload_B;
    end else begin
        output_V_data_V_1_data_out = output_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (or_cond_reg_825_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (or_cond_reg_825_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        output_V_data_V_1_vld_in = 1'b1;
    end else begin
        output_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (or_cond_reg_825_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (or_cond_reg_825_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        output_V_keep_V_1_vld_in = 1'b1;
    end else begin
        output_V_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_01001) & (or_cond_reg_825_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        output_V_last_V_1_data_in = tmp_last_V_reg_834_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage4_01001) & (or_cond_reg_825_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        output_V_last_V_1_data_in = tmp_last_V_1_reg_829_pp0_iter3_reg;
    end else begin
        output_V_last_V_1_data_in = 'bx;
    end
end

always @ (*) begin
    if ((output_V_last_V_1_sel == 1'b1)) begin
        output_V_last_V_1_data_out = output_V_last_V_1_payload_B;
    end else begin
        output_V_last_V_1_data_out = output_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (or_cond_reg_825_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (or_cond_reg_825_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        output_V_last_V_1_vld_in = 1'b1;
    end else begin
        output_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (or_cond_reg_825_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (or_cond_reg_825_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        output_V_strb_V_1_vld_in = 1'b1;
    end else begin
        output_V_strb_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4) & (or_cond_reg_825_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage4) & (or_cond_reg_825_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((or_cond_reg_825_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((or_cond_reg_825_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        output_r_TDATA_blk_n = output_V_data_V_1_state[1'd1];
    end else begin
        output_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond1_fu_287_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond1_fu_287_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((~((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter4 == 1'b1)) & (1'b0 == ap_block_pp0_stage4_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_state31 : begin
            if ((~((output_V_last_V_1_ack_in == 1'b0) | (output_V_strb_V_1_ack_in == 1'b0) | (output_V_keep_V_1_ack_in == 1'b0) | (output_V_data_V_1_ack_in == 1'b0)) & (output_V_last_V_1_state[1'd0] == 1'b0) & (output_V_strb_V_1_state[1'd0] == 1'b0) & (output_V_keep_V_1_state[1'd0] == 1'b0) & (output_V_data_V_1_state[1'd0] == 1'b0) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((1'b1 == ap_block_state29_io) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((1'b1 == ap_block_state29_io) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = (((1'b1 == ap_block_state24_io) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b1 == ap_block_state30_io) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = (((1'b1 == ap_block_state24_io) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b1 == ap_block_state30_io) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_11001 = (((1'b1 == ap_block_state25_io) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((exitcond1_reg_804 == 1'd0) & (input_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = (((1'b1 == ap_block_state25_io) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((exitcond1_reg_804 == 1'd0) & (input_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_state10_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage5_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state24_io = ((or_cond_reg_825_pp0_iter3_reg == 1'd0) & (output_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state24_pp0_stage4_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state25_io = ((or_cond_reg_825_pp0_iter3_reg == 1'd0) & (output_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state25_pp0_stage5_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state29_io = ((or_cond_reg_825_pp0_iter4_reg == 1'd1) & (output_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state29_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state30_io = ((or_cond_reg_825_pp0_iter4_reg == 1'd1) & (output_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state30_pp0_stage4_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state31 = ((output_V_last_V_1_ack_in == 1'b0) | (output_V_strb_V_1_ack_in == 1'b0) | (output_V_keep_V_1_ack_in == 1'b0) | (output_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage5_iter0 = ((exitcond1_reg_804 == 1'd0) & (input_V_data_V_0_vld_out == 1'b0));
end

assign ap_block_state8_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign col_1_fu_409_p2 = ($signed(col_reg_245) + $signed(32'd1));

assign exitcond1_fu_287_p2 = ((ap_phi_mux_i_phi_fu_261_p4 == 16'd50625) ? 1'b1 : 1'b0);

assign grp_fu_268_p0 = tmp_17_reg_929;

assign grp_fu_276_p2 = ((ap_phi_mux_i_phi_fu_261_p4 == 16'd50624) ? 1'b1 : 1'b0);

assign grp_fu_797_p0 = gy_cast_cast_fu_615_p1;

assign grp_fu_797_p1 = gy_cast_cast_fu_615_p1;

assign gx_cast_cast_fu_573_p1 = $signed(gx_reg_909);

assign gx_fu_552_p2 = (tmp_10_cast_fu_527_p1 + tmp_10_fu_546_p2);

assign gy_cast_cast_fu_615_p1 = $signed(gy_reg_919);

assign gy_fu_609_p2 = (tmp_18_cast_fu_596_p1 + tmp_14_fu_603_p2);

assign i_1_fu_293_p2 = (ap_phi_mux_i_phi_fu_261_p4 + 16'd1);

assign icmp4_fu_351_p2 = (($signed(tmp_22_fu_341_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp9_fu_772_p2 = (($signed(tmp_35_fu_762_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_fu_335_p2 = (($signed(tmp_20_fu_325_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign input_V_data_V_0_ack_in = input_V_data_V_0_state[1'd1];

assign input_V_data_V_0_load_A = (input_V_data_V_0_state_cmp_full & ~input_V_data_V_0_sel_wr);

assign input_V_data_V_0_load_B = (input_V_data_V_0_state_cmp_full & input_V_data_V_0_sel_wr);

assign input_V_data_V_0_sel = input_V_data_V_0_sel_rd;

assign input_V_data_V_0_state_cmp_full = ((input_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign input_V_data_V_0_vld_in = input_r_TVALID;

assign input_V_data_V_0_vld_out = input_V_data_V_0_state[1'd0];

assign input_V_last_V_0_vld_in = input_r_TVALID;

assign input_r_TREADY = input_V_last_V_0_state[1'd1];

assign isNeg_fu_671_p3 = sh_assign_fu_665_p2[32'd8];

assign mantissa_V_1_cast2_fu_657_p1 = mantissa_V_fu_647_p4;

assign mantissa_V_fu_647_p4 = {{{{1'd1}, {tmp_V_1_fu_643_p1}}}, {1'd0}};

assign or_cond_fu_357_p2 = (icmp_fu_335_p2 & icmp4_fu_351_p2);

assign output_V_data_V_1_ack_in = output_V_data_V_1_state[1'd1];

assign output_V_data_V_1_ack_out = output_r_TREADY;

assign output_V_data_V_1_load_A = (output_V_data_V_1_state_cmp_full & ~output_V_data_V_1_sel_wr);

assign output_V_data_V_1_load_B = (output_V_data_V_1_state_cmp_full & output_V_data_V_1_sel_wr);

assign output_V_data_V_1_sel = output_V_data_V_1_sel_rd;

assign output_V_data_V_1_state_cmp_full = ((output_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_V_data_V_1_vld_out = output_V_data_V_1_state[1'd0];

assign output_V_keep_V_1_ack_in = output_V_keep_V_1_state[1'd1];

assign output_V_keep_V_1_ack_out = output_r_TREADY;

assign output_V_keep_V_1_data_out = 1'd0;

assign output_V_keep_V_1_sel = output_V_keep_V_1_sel_rd;

assign output_V_keep_V_1_vld_out = output_V_keep_V_1_state[1'd0];

assign output_V_last_V_1_ack_in = output_V_last_V_1_state[1'd1];

assign output_V_last_V_1_ack_out = output_r_TREADY;

assign output_V_last_V_1_load_A = (output_V_last_V_1_state_cmp_full & ~output_V_last_V_1_sel_wr);

assign output_V_last_V_1_load_B = (output_V_last_V_1_state_cmp_full & output_V_last_V_1_sel_wr);

assign output_V_last_V_1_sel = output_V_last_V_1_sel_rd;

assign output_V_last_V_1_state_cmp_full = ((output_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_V_last_V_1_vld_out = output_V_last_V_1_state[1'd0];

assign output_V_strb_V_1_ack_in = output_V_strb_V_1_state[1'd1];

assign output_V_strb_V_1_ack_out = output_r_TREADY;

assign output_V_strb_V_1_data_out = 1'd0;

assign output_V_strb_V_1_sel = output_V_strb_V_1_sel_rd;

assign output_V_strb_V_1_vld_out = output_V_strb_V_1_state[1'd0];

assign output_r_TDATA = output_V_data_V_1_data_out;

assign output_r_TKEEP = output_V_keep_V_1_data_out;

assign output_r_TLAST = output_V_last_V_1_data_out;

assign output_r_TSTRB = output_V_strb_V_1_data_out;

assign output_r_TVALID = output_V_last_V_1_state[1'd0];

assign p_Val2_5_fu_743_p3 = ((isNeg_fu_671_p3[0:0] === 1'b1) ? tmp_29_fu_729_p1 : tmp_30_fu_733_p4);

assign p_Val2_6_fu_756_p3 = ((p_Result_s_reg_949[0:0] === 1'b1) ? result_V_1_fu_751_p2 : p_Val2_5_reg_954);

assign p_Val2_s_fu_622_p1 = x_assign_reg_944;

assign p_row_fu_427_p3 = ((tmp_21_fu_415_p2[0:0] === 1'b1) ? row_1_fu_421_p2 : row_reg_233);

assign p_s_fu_435_p3 = ((tmp_21_fu_415_p2[0:0] === 1'b1) ? 32'd0 : col_1_fu_409_p2);

assign r_V_1_fu_715_p2 = mantissa_V_1_cast2_fu_657_p1 << tmp_i_i_i_8_fu_705_p1;

assign r_V_fu_709_p2 = mantissa_V_fu_647_p4 >> sh_assign_2_cast_cas_fu_701_p1;

assign result_V_1_fu_751_p2 = (32'd0 - p_Val2_5_reg_954);

assign row_1_fu_421_p2 = (row_reg_233 + 32'd1);

assign sh_assign_2_cast_cas_fu_701_p1 = ush_fu_689_p3;

assign sh_assign_2_cast_fu_697_p1 = ush_fu_689_p3;

assign sh_assign_fu_665_p2 = ($signed(9'd385) + $signed(tmp_i_i_i_i_cast1_fu_661_p1));

assign sum87_neg_fu_561_p2 = (tmp_4_cast4_fu_515_p1 - sum_cast_fu_558_p1);

assign sum_cast_fu_558_p1 = sum_reg_899;

assign sum_fu_471_p2 = (tmp_5_cast_fu_457_p1 + tmp_6_cast_fu_461_p1);

assign tmp_10_cast3_fu_523_p1 = input_V_data_V_0_data_out;

assign tmp_10_cast_fu_527_p1 = input_V_data_V_0_data_out;

assign tmp_10_fu_546_p2 = (tmp_9_fu_540_p2 - tmp_4_cast_fu_519_p1);

assign tmp_11_cast_fu_531_p1 = $signed(tmp_6_reg_894);

assign tmp_11_fu_576_p3 = {{reg_282}, {1'd0}};

assign tmp_12_fu_588_p3 = {{line_buffer_q1}, {1'd0}};

assign tmp_13_fu_567_p2 = (tmp_10_cast3_fu_523_p1 + sum87_neg_fu_561_p2);

assign tmp_14_fu_603_p2 = ($signed(tmp_19_cast_fu_600_p1) - $signed(tmp_16_cast_fu_584_p1));

assign tmp_15_fu_791_p0 = gx_cast_cast_fu_573_p1;

assign tmp_15_fu_791_p1 = gx_cast_cast_fu_573_p1;

assign tmp_16_cast_fu_584_p1 = tmp_11_fu_576_p3;

assign tmp_18_cast_fu_596_p1 = tmp_12_fu_588_p3;

assign tmp_19_cast_fu_600_p1 = $signed(tmp_13_reg_914);

assign tmp_19_fu_314_p2 = (11'd450 + tmp_2_fu_299_p1);

assign tmp_1_fu_363_p1 = col_reg_245;

assign tmp_20_fu_325_p4 = {{ap_phi_mux_row_phi_fu_237_p4[31:1]}};

assign tmp_21_fu_415_p2 = ((col_1_fu_409_p2 == 32'd225) ? 1'b1 : 1'b0);

assign tmp_22_cast_fu_309_p1 = $signed(tmp_3_fu_303_p2);

assign tmp_22_fu_341_p4 = {{ap_phi_mux_col_phi_fu_249_p4[31:1]}};

assign tmp_23_cast_fu_320_p1 = $signed(tmp_19_fu_314_p2);

assign tmp_23_fu_379_p1 = tmp_4_fu_368_p2[10:0];

assign tmp_24_cast_fu_389_p1 = $signed(tmp_24_fu_383_p2);

assign tmp_24_fu_383_p2 = (11'd225 + tmp_23_fu_379_p1);

assign tmp_25_cast_fu_448_p1 = $signed(tmp_25_fu_443_p2);

assign tmp_25_fu_443_p2 = (11'd450 + tmp_23_reg_839);

assign tmp_26_cast_fu_487_p1 = $signed(tmp_26_fu_482_p2);

assign tmp_26_fu_482_p2 = (11'd450 + tmp_27_reg_859);

assign tmp_27_fu_400_p1 = tmp_31_0_1_fu_394_p2[10:0];

assign tmp_29_fu_729_p1 = tmp_34_fu_721_p3;

assign tmp_2_fu_299_p1 = ap_phi_mux_col_phi_fu_249_p4[10:0];

assign tmp_30_fu_733_p4 = {{r_V_1_fu_715_p2[55:24]}};

assign tmp_31_0_1_fu_394_p2 = ($signed(32'd4294967295) + $signed(col_reg_245));

assign tmp_32_0_1_fu_453_p1 = tmp_31_0_1_reg_854;

assign tmp_32_0_2_fu_404_p1 = $unsigned(col_reg_245);

assign tmp_34_fu_721_p3 = r_V_fu_709_p2[32'd24];

assign tmp_35_fu_762_p4 = {{p_Val2_6_fu_756_p3[31:8]}};

assign tmp_36_fu_778_p1 = p_Val2_6_fu_756_p3[7:0];

assign tmp_3_fu_303_p2 = (11'd225 + tmp_2_fu_299_p1);

assign tmp_4_cast4_fu_515_p1 = line_buffer_q1;

assign tmp_4_cast_fu_519_p1 = line_buffer_q1;

assign tmp_4_fu_368_p2 = ($signed(32'd4294967294) + $signed(col_reg_245));

assign tmp_5_cast_fu_457_p1 = reg_282;

assign tmp_5_fu_374_p1 = tmp_4_fu_368_p2;

assign tmp_6_cast_fu_461_p1 = line_buffer_q0;

assign tmp_6_fu_465_p2 = (tmp_6_cast_fu_461_p1 - tmp_5_cast_fu_457_p1);

assign tmp_7_fu_534_p2 = ($signed(tmp_11_cast_fu_531_p1) - $signed(tmp_8_cast_fu_499_p1));

assign tmp_8_cast_fu_499_p1 = tmp_8_fu_492_p3;

assign tmp_8_fu_492_p3 = {{line_buffer_load_5_reg_869}, {1'd0}};

assign tmp_9_fu_540_p2 = (tmp_cast_fu_511_p1 + tmp_7_fu_534_p2);

assign tmp_V_1_fu_643_p1 = p_Val2_s_fu_622_p1[22:0];

assign tmp_V_fu_633_p4 = {{p_Val2_s_fu_622_p1[30:23]}};

assign tmp_cast_fu_511_p1 = tmp_s_fu_503_p3;

assign tmp_data_V_fu_782_p3 = ((icmp9_fu_772_p2[0:0] === 1'b1) ? 8'd255 : tmp_36_fu_778_p1);

assign tmp_i_i_i_8_fu_705_p1 = $unsigned(sh_assign_2_cast_fu_697_p1);

assign tmp_i_i_i_cast_fu_685_p1 = $signed(tmp_i_i_i_fu_679_p2);

assign tmp_i_i_i_fu_679_p2 = (8'd127 - tmp_V_fu_633_p4);

assign tmp_i_i_i_i_cast1_fu_661_p1 = tmp_V_fu_633_p4;

assign tmp_s_fu_503_p3 = {{reg_282}, {1'd0}};

assign ush_fu_689_p3 = ((isNeg_fu_671_p3[0:0] === 1'b1) ? tmp_i_i_i_cast_fu_685_p1 : sh_assign_fu_665_p2);

endmodule //sobel
